// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static void aCT_CAll(IContext context, myfirstmodule.proxies.person _person)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("person", _person == null ? null : _person.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_CAll").withParams(params).execute(context);
	}
	public static void demo(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.demo").withParams(params).execute(context);
	}
	public static void newdateage(IContext context, myfirstmodule.proxies.person _person)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("person", _person == null ? null : _person.getMendixObject());
		Core.microflowCall("MyFirstModule.newdateage").withParams(params).execute(context);
	}
	public static void oen_leave(IContext context, myfirstmodule.proxies.person _person)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("person", _person == null ? null : _person.getMendixObject());
		Core.microflowCall("MyFirstModule.oen_leave").withParams(params).execute(context);
	}
}
